local pool = CacheManager.Instance:GetPool(CacheDefine.PoolType.Test,true)

local obj = CacheManager.Instance:Get(CacheDefine.PoolType.Test)
pool:Log()
CacheManager.Instance:Recycle(obj)
pool:Log()
local obj = CacheManager.Instance:Get(CacheDefine.PoolType.Test)
pool:Log()
CacheManager.Instance:Recycle(obj)
pool:Log()
CacheManager.Instance:Get(CacheDefine.PoolType.Test)
pool:Log()
CacheManager.Instance:Get(CacheDefine.PoolType.Test)
pool:Log()
CacheManager.Instance:Get(CacheDefine.PoolType.Test)
pool:Log()